add contribution file
cisco-open/otel-dotnet pull request #32
Opened 2022-07-31 14:28 UTC by avzis

2022-08-01 12:40 UTC, osherv approved these changes

2022-08-01 16:19 UTC, samimusallam requested changes

2022-08-01 16:19 UTC, samimusallam commented on CONTRIBUTION.md
> +.NET 6
Can we change this to ".NET 6.0+"?

2022-08-01 16:19 UTC, samimusallam commented on CONTRIBUTION.md
> +After setting up the repo you will be able to work with every scope package individually (using the familiar npm commands)
No need for the npm part

2022-08-01 16:19 UTC, samimusallam commented on CONTRIBUTION.md
> +#### Conventional commit
We dont really have anything setup for this section, so Im not sure if we should keep this or not

2022-08-02 10:26 UTC, samimusallam approved these changes

2022-08-02 10:27 UTC, merged